export const GETTING_STARTED = [
  {
    name: "Getting Started",
    subcategories: [
      "Introduction",
      "Installation",
      // "Wave Text",
      // "Shiny Text",
      // "Gradient Text",
      // "Decrypt Hover",
      // "Flip Text",
      // "Word Cloud",
      // "Count Up",
    ],
  },
];

export const CATEGORIES = [
  {
    name: "Components",
    subcategories: [
      "Button",
      // "Cards",
      "Input",
      "Bento",
      "Modal",
      "Sheet",
    ],
  },
  {
    name: "Text",
    subcategories: [
      "Shimmer",
      "Loader",
      // "Cards",
      // "Input",
      // "Bento",
      // "Modal",
      // "Sheet",
    ],
  },
  {
    name: "Molecules",
    subcategories: [
      "Authentication",
      // "Wave Text",
      // "Shiny Text",
      // "Gradient Text",
      // "Decrypt Hover",
      // "Flip Text",
      // "Word Cloud",
      // "Count Up",
    ],
  },
  {
    name: "Animations",
    subcategories: [
      "Loaders",
      // "Blob Cursor",
      // "Follow Cursor",
      // "Trail Cursor",
      // "Emoji Cursor",
      // "Wave Cursor",
      // "Liquid Cursor",
      // "Distortion Cursor",
      // "Crosshair",
      // "Crystal Ball",
      // "Spotlights",
      // "Magnet",
      // "Fade",
      // "Persistent Drag",
      // "Beam Border",
      // "Star Border",
      // "Clump",
      // "Ballpit",
    ],
  },
  // {
  //   name: "Backgrounds",
  //   subcategories: [
  //     "Hyperspeed",
  //     "Grid Motion",
  //     "Squares",
  //     "Particles",
  //     "Grain",
  //     "Threads",
  //     "Gradient",
  //     "Dots",
  //     "Waves",
  //   ],
  // },
];
